# STAT306 project

## 1. Introduction

#### Motivation

Nowadays, as technological advancements revolutionize industries, digital car trading platforms have emerged as vital marketplaces, transforming the automotive market and the way people buy and sell second-hand vehicles. Notably, CarDekho.com is a well-known car trading platform based in India. The primary motivation for this analysis stems from the growing importance of platforms like CarDekho.com in connecting buyers and sellers. In particular, for buyers, understanding the relationship between car traits and pricing can facilitate purchasing decisions, and help assess whether a car is priced fairly. Meanwhile, for sellers, the insights into pricing trends can help attract more potential customers while still setting competitive selling prices, determining the optimal price for their listings. Thus, this study aims to investigate a deeper understanding of these relationships by addressing the following research questions:

-   Is there a linear relationship between the selling price and the kilometers driven by the car?

-   What categorical variables are associated with the selling price, and how do these variables influence pricing?

-   What regression model can effectively explain and interpret the relationships in the data?

By answering these questions, we aim to develop a statistical model that contributes to the car trading marked by offering data-driven insights.

#### Dataset

The dataset analyzed in this report contains information about second-hand cars provided by CarDekho.com (<https://www.cardekho.com/>). The dataset was published on Kaggle (<https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho/data>) on June 26, 2020.

The following is a description of the variables found in the dataset:

| Variables     | Type        | Descriptions                                                            |
|-----------------------|--------------------|-----------------------------|
| name          | categorical | the name of the car; start with brand name which is a possible factor   |
| year          | continuous  | the year of the car when it was bought (in years)                       |
| selling_price | continuous  | the price of car when it was sold (in Indian Rupee (INR))               |
| km_driven     | continuous  | the distance that the car is driven (in kilometers)                     |
| fuel          | categorical | the fuel type of the car; 5 levels (CNG/Diesel/Electric/LPG/Petrol)     |
| seller_type   | categorical | the type of the seller; 3 levels (Dealer, Individual, Trustmark Dealer) |
| transmission  | categorical | the type of gear transmission; 2 levels (Manual, Automatic)             |
| owner         | categorical | the number of previous owners; 5 levels                                 |

By setting selling_price as our response, we have a total of 5 categorical variables and 2 continuous variables. 

## 2. Exploratory Analysis

TODO

-   add a new column "brand", based on the name of cars

<!-- -->

-   scatter plots (by categories)

-   boxplots

-   possible log transformation (if highly right-skewed)

-   check multicolinearity (using VIF)

### 

## 3. Statistical Analysis

## 4. Discussion
